language: node_js
node_js:
  - 6
  - 8
  - 10
  - 11

notifications:
  email: false

before_install:
  - npm install -g codecov
script:
  - npm run format
  - make docker-test
  - codecov

branches:
  except:
    - '/^v\d+\.\d+\.\d+$/'

jobs:
  include:
    - stage: deploy
      if: branch == master && !fork
      node_js: node # pre-installed version
      script:
        - npm install -g semantic-release
        - semantic-release